//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Startday { get; set; }
        public Nullable<decimal> TotalPrices { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
