//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thiennhanEntities : DbContext
    {
        public thiennhanEntities()
            : base("name=thiennhanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookingDetail> BookingDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourAttribute> TourAttributes { get; set; }
        public virtual DbSet<TourTransport> TourTransports { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
