//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAttribute
    {
        public int ID { get; set; }
        public Nullable<int> IDAttribute { get; set; }
        public Nullable<int> IDTour { get; set; }
        public Nullable<System.DateTime> Addate { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
